import { Controller } from "@hotwired/stimulus"
import {
  createIcons,
  Home,
  GraduationCap,
  BookOpen,
  Phone,
  Heart,
  UserPlus,
  ArrowDown,
  Calendar,
  Star,
  ArrowRight,
  ArrowLeft,
  Clock,
  PlayCircle,
  Users,
  User,
  Keyboard,
  Volume2,
  Contrast,
  Type,
  Captions,
  HeartHandshake,
  ShieldCheck,
  LogIn,
  Mail,
  MessageCircle,
  MapPin,
  Send,
  XCircle,
  // --- Ícones da tela de Cadastro ---
  Lock,
  Eye,
  EyeOff,
  Contact,
  BadgePlus,
  BadgeCheck,
  // --- Novos ícones para a tela de Completar Perfil ---
  Map,
  Briefcase,
  FolderOpen,
  ChevronDown,
  EarOff,
  Activity,
  Brain,
  BrainCircuit,
  Folder,
  FileText,
  CloudUpload,
  // --- Ícones adicionados para o Perfil Social, Documentos e Ações ---
  Edit3,
  IdCard,
  DollarSign,
  PlusCircle,
  FileCheck,
  Paperclip,
  ExternalLink,
  // -- Icones de dashboard
  LayoutDashboard,
  BarChart2,
  UserCheck,
  AlertCircle,
  FileClock,
  Check,
  X,
  Image,
  Shield,
  Menu
} from "lucide"

export default class extends Controller {
  connect() {
    createIcons({
      icons: {
        Home,
        GraduationCap,
        BookOpen,
        Phone,
        Heart,
        UserPlus,
        ArrowDown,
        Calendar,
        Star,
        ArrowRight,
        ArrowLeft,
        Clock,
        PlayCircle,
        Users,
        User,
        Keyboard,
        Volume2,
        Contrast,
        Type,
        Captions,
        HeartHandshake,
        ShieldCheck,
        LogIn,
        Mail,
        MessageCircle,
        MapPin,
        Send,
        Lock,
        Eye,
        EyeOff,
        Contact,
        BadgePlus,
        BadgeCheck,
        // --- Novos ícones ---
        Map,
        Briefcase,
        FolderOpen,
        ChevronDown,
        EarOff,
        Activity,
        Brain,
        BrainCircuit,
        Folder,
        FileText,
        CloudUpload,
        XCircle,
        // Icones novos dashboard
        LayoutDashboard,
        BarChart2,
        UserCheck,
        AlertCircle,
        FileClock,
        Check,
        X,
        Image,
        Shield,
        Menu,
        // --- Ícones mapeados  ---
        Edit3,
        IdCard,
        DollarSign,
        PlusCircle,
        FileCheck,
        Paperclip,
        ExternalLink,
      },
    })
  }
}
