import { Controller } from "@hotwired/stimulus";
import {
  createIcons,
  Home,
  GraduationCap,
  BookOpen,
  Phone,
  Heart,
  UserPlus,
  ArrowDown,
  Calendar,
  Star,
  ArrowRight,
  Clock,
  PlayCircle,
  Users,
  User,
  Keyboard,
  Volume2,
  Contrast,
  Type,
  Captions,
  HeartHandshake,
  ShieldCheck,
  LogIn,
  Mail,
  MessageCircle,
  MapPin,
  Send,
  // --- Ícones da tela de Cadastro ---
  Lock,
  Eye,
  EyeOff,
  Contact,
  BadgePlus,
  // --- Novos ícones para a tela de Completar Perfil ---
  Map,
  Briefcase,
  FolderOpen,
  ChevronDown,
  EarOff,
  Activity,
  Brain,
  BrainCircuit,
  Folder,
  FileText,
  CloudUpload,
} from "lucide";

export default class extends Controller {
  connect() {
    createIcons({
      icons: {
        Home,
        GraduationCap,
        BookOpen,
        Phone,
        Heart,
        UserPlus,
        ArrowDown,
        Calendar,
        Star,
        ArrowRight,
        Clock,
        PlayCircle,
        Users,
        User,
        Keyboard,
        Volume2,
        Contrast,
        Type,
        Captions,
        HeartHandshake,
        ShieldCheck,
        LogIn,
        Mail,
        MessageCircle,
        MapPin,
        Send,
        Lock,
        Eye,
        EyeOff,
        Contact,
        BadgePlus,
        // --- Novos ícones ---
        Map,
        Briefcase,
        FolderOpen,
        ChevronDown,
        EarOff,
        Activity,
        Brain,
        BrainCircuit,
        Folder,
        FileText,
        CloudUpload,
      },
    });
  }
}
